### PR TITLE
Use bits-ui version with onCloseAutoFocus bugfix

### LINKED ISSUE #1853: Error when popup removed from dom before closing finishes
**Describe the bug**
Since updating Bits UI when any sort of popup is removed from the dom while it's open there's an error. 

**To Reproduce**

1. use mobile view (small window)
2. on project page open the sidebar
3. click close project
4. see error: `__privateGet(...).onCloseAutoFocus.current is not a function`

Image

other examples where it shows up:
- delete sense dialog
- create entry dialog
- delete entry menu
- remove complex form

**Expected behavior**
There should be no error. We should find out if this is just a bug in Bits, or if we need to not remove popups from the dom while they're open. I hope it's a bug as there's a lot of random places it shows up.

### PR DESCRIPTION
**Pull request by rmunn**
Fixes #1853.

### CODE REVIEW

**Comment by rmunn** [comment]
I've confirmed that this fixes the bug. On the `feat/admins-can-download-any-crdt-project` branch (PR #1829), I can trigger the `onCloseAutoFocus` error consistently by opening the "download project not listed" dialog, then closing it again. After bumping the `bits-ui` version to 2.8.13, I can no longer get the `onCloseAutoFocus` error to show up.
